{
 "title": "Story Validator Dashboard",
 "description": "This dashboard is proudly built and maintained by TTT Labs. Our goal is to create innovative solutions and tools that empower communities and blockchain projects to grow and succeed. Through continuous improvements, we aim to provide insightful metrics and intuitive interfaces for users to stay informed and make data-driven decisions effectively.",
 "tags": [
  "Blockchain",
  "Cosmos",
  "Story",
  "TTT Labs",
  "NickoLam",
  "OsamaPikachu"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cometbft_consensus_height,chain_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cometbft_consensus_height{chain_id=\"$chain_id\"},instance)"
    }
   },
   { "name": "origin_prometheus", "label": "Origin_prom", "query": { "query": "label_values()" } },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "version",
    "query": {
     "query": "label_values(lib_buildinfo_version,version)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://tienthuattoan.com/assest/img/logo.png\" />"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n  <h1 style=\"color: #ADD8E6; display: flex; align-items: center; justify-content: center; gap: 15px;\">\n    <img src=\"https://img.cryptorank.io/coins/150x150.story_protocol1693995191319.png\" \n         style=\"width: 75px; height: 75px;\" />\n    <span style=\"font-size: 75px; font-weight: bold;\">TORY VALIDATOR MONITORING</span>\n  </h1>\n</div>"
   }
  },
  {
   "title": "Story-Chain: $chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 4 },
   "options": {
    "content": "<div style=\"text-align: center; font-size: 17px; font-weight: bold; margin-top: 50px; line-height: 0.7;\">\n\n  <img src=\"https://img.cryptorank.io/coins/150x150.story_protocol1693995191319.png\"\n       alt=\"Story Protocol Logo\" style=\"width: 40px; height: 40px; margin-bottom: 5px;\" />\n\n  <div style=\"display: flex; align-items: center; justify-content: center; margin-bottom: -5px;\">\n    <span style=\"margin-right: 5px;\">Blockchain:</span>\n    <img src=\"https://snapshots.tienthuattoan.com/testnet/story/story-white-text.png\" \n         alt=\"Blockchain Logo\" style=\"width: 70px; height: 50px;\" />\n  </div>\n\n  <div style=\"text-align: center;\">\n    Network: <span id=\"network-name\" style=\"color: #80ffbf;\">$chain_id</span>\n  </div>\n  <div style=\"text-align: center;\">\n    Version: <span id=\"network-name\" style=\"color: #80ffbf;font-size: 16px;\">$version</span>\n  </div>\n</div>"
   },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chain Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cosmos_tx_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total power validators",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Gas Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 4 },
   "targets": [
    { "expr": "cosmos_tx_gas_used", "legendFormat": "Gas" }
   ]
  },
  {
   "title": "Tokens Info",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "token_supply{chain_id=\"$chain_id\"}/1000000000",
     "legendFormat": "Supply"
    },
    {
     "expr": "token_bonded{chain_id=\"$chain_id\"}/1000000000",
     "legendFormat": "Bonded"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_sum{chain_id=\"$chain_id\", instance=\"$instance\"} / cometbft_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Token Alias",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 7 },
   "options": {
    "content": "<div class=\"container\" style=\"display: flex; align-items: center; justify-content: center; gap: 5px; height: 100%;\">\n  <img src=\"https://img.cryptorank.io/coins/story_protocol1693995191319.png\" \n       alt=\"Story Protocol Logo\" style=\"width: 1em; height: 1em;\">\n  <span class=\"ip-text\" style=\"font-size: 1em; font-weight: bold;\">IP</span>\n</div>"
   },
   "targets": [
    { "expr": "token_info_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validators_total{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validators_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tx successful",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cosmos_tx_successful", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Token denom",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "options": {
    "content": "<div class=\"container\" style=\"display: flex; align-items: center; justify-content: center; height: 100%; font-size: 1em; font-weight: bold;\">\n  stake\n</div>\n"
   },
   "targets": [
    { "expr": "token_info_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "Node Validator Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Missing Block",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Block"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 15, "x": 0, "y": 15 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n  <h1 style=\"color: #9999ff; display: flex; align-items: center; justify-content: center\">\n    <span style=\"font-size: 13px; font-weight: bold;\">STORY NODE INFO</span>\n  </h1>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 15, "y": 15 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n  <h1 style=\"color: #33ffff; display: flex; align-items: center; justify-content: center\">\n    <span style=\"font-size: 13px; font-weight: bold;\">STORY VALIDATOR INFO</span>\n  </h1>\n</div>"
   }
  },
  {
   "title": "Node Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_uname_info{chain_id=\"$chain_id\"} - 0"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{chain_id=\"$chain_id\"}) by (instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{chain_id=\"$chain_id\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=\"$instance\"}) by (instance) /8",
     "legendFormat": "Cores"
    },
    {
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{chain_id=\"$chain_id\"}[$__interval])) by (instance)) * 100",
     "legendFormat": "CPU used%"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{chain_id=\"$chain_id\"} / (node_memory_MemTotal_bytes{chain_id=\"$chain_id\"}))) * 100",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{instance=\"$chain_id\"}[$__interval])) by (instance)",
     "legendFormat": "Disk read%"
    },
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{chain_id=\"$chain_id\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}/node_filesystem_size_bytes{chain_id=\"$chain_id\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}) by (instance)) * 100",
     "legendFormat": "/ used%"
    },
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{chain_id=\"$chain_id\",mountpoint=~\"/home\",fstype=~\"ext.?|xfs\"}/node_filesystem_size_bytes{chain_id=\"$chain_id\",mountpoint=~\"/home\",fstype=~\"ext.?|xfs\"}) by (instance)) * 100",
     "legendFormat": "/home used%"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{chain_id=\"$chain_id\"}[$__interval])) by (instance)",
     "legendFormat": "Disk write%"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{chain_id=\"$chain_id\"}[$__interval])*8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{chain_id=\"$chain_id\"}[$__interval])*8) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Moniker",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "targets": [
    { "expr": "validator_info_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jailed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validator_jailed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tombstoned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validator_tombstoned", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bonded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(delegator_amount)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Account Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 19 },
   "targets": [
    { "expr": "validator_info_info", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "targets": [
    { "expr": "lib_buildinfo_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node block height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tm_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sync status Story",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_sync_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "cometbft_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Delegators",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "targets": [
    { "expr": "delegator_amount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voting Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "cometbft_consensus_missing_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power (%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_round_voting_power_percent{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "{{vote_type}}"
    }
   ]
  },
  {
   "title": "Confirmed Tx",
   "type": "bargauge",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Txs"
    },
    {
     "expr": "increase(cometbft_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}[1m])",
     "legendFormat": "Txs per minute"
    }
   ]
  },
  {
   "title": "Unconfirmed Tx (in mempool)",
   "type": "bargauge",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{chain_id=\"$chain_id\"}",
     "legendFormat": "Txs"
    },
    {
     "expr": "increase(cometbft_mempool_size{chain_id=\"$chain_id\"}[1m])",
     "legendFormat": "Txs per minute"
    }
   ]
  },
  {
   "title": "Block Process Time Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "increase(cometbft_state_block_processing_time_count{chain_id=\"$chain_id\", instance=\"$instance\"}[5m])",
     "legendFormat": "Block Time - 5m"
    },
    {
     "expr": "increase(cometbft_state_block_processing_time_count{chain_id=\"$chain_id\", instance=\"$instance\"}[1h])",
     "legendFormat": "Block Time - 1h"
    },
    {
     "expr": "increase(cometbft_state_block_processing_time_count{chain_id=\"$chain_id\", instance=\"$instance\"}[3h])",
     "legendFormat": "Block Time - 3h"
    },
    {
     "expr": "increase(cometbft_state_block_processing_time_count{chain_id=\"$chain_id\", instance=\"$instance\"}[6h])",
     "legendFormat": "Block Time - 6h"
    },
    {
     "expr": "increase(cometbft_state_block_processing_time_count{chain_id=\"$chain_id\", instance=\"$instance\"}[12h])",
     "legendFormat": "Block Time - 12h"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Instance Overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
     "legendFormat": "Used RAM Memory"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$instance\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$instance\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "【$instance】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 49 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    }
   ]
  },
  {
   "title": "Used Max Mount($maxmount)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$instance\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$instance\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'})"
    }
   ]
  },
  {
   "title": "Free inodes:$maxmount ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{instance=~\"$instance\",mountpoint=\"/\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total filefd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cometbft_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cometbft_p2p_peer_send_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}